# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Memo's Notebook"
layout: default 
email: mehmetkorkut77@gmail.com
description: Welcome to my personal website! Check posts to see my Portfolio Projects and Blog. You can find my CV and more information about me on About section.
twitter_username: MehmetK85110144
github_username: MehmetKorkut
minimal_mistakes_skin: default
header:
  overlay_image: "/assets/images/header.jpg"
  overlay_filter: 0.5 # same as adding an opacity of 0.5 to a black background
  caption: "Photo credit: [**Unsplash**](https://unsplash.com)"
  actions:
    - label: "More Info"
      url: "https://unsplash.com"



# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-categories

author:
  name   : "Mehmet Korkut"
  avatar : "/assets/images/MK3.jpg"
  bio    : "Data Analyst @SeeD"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.mehmetkorkut.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MehmetK85110144"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MehmetKorkut"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/memokorkut/"


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MehmetK85110144"
    - label: "GitHub"
      icon: "https://github.com/MehmetKorkut"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/memokorkut/"

defaults:
  # _posts
  - scope:
      path: "portfolio"
      type: portfolio
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      category_links: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true



